<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderSaga.Shared\OrderSaga.Shared.csproj" />
    <ProjectReference Include="..\OrderSaga.Orchestration\OrderSaga.Orchestration.csproj" />
    <ProjectReference Include="..\OrderSaga.Orchestration.Messaging\OrderSaga.Orchestration.Messaging.csproj" />
    <ProjectReference Include="..\Saga.Persistence\Saga.Persistence.csproj" />
  </ItemGroup>

</Project>
