<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Inventory.Domain\Inventory.Domain.csproj" />
    <ProjectReference Include="..\OrderSaga.Shared\OrderSaga.Shared.csproj" />
  </ItemGroup>

</Project>
